### ISSUE TITLE
changelogs

### ISSUE THREAD

**Issue by kreezxil** [daniel-araujo/click4ever#1]
all these updates you have been making lately,

are they just things you've noticed and felt was needed or were they response to issues? if issues, please don't delete issues but mark them as closed and indicated which patched fixed them.

Thanks.

**Comment by daniel-araujo** [comment]
Hello.

No issues were harmed in the making of this program. Yours is #1.

The changes were impromptu.

- I fixed timing and performance issues.
- Added command line arguments so that you can customize delays and which button to click.
- Autotools was replaced by CMake and the code-base was converted to C++ out of convenience.

I will provide changelogs in future releases. Thank you for your feedback.

**Comment by kreezxil** [comment]
thanks. When tiny programs begin updating frequently without changelogs I
get really curious. I tend to excuse one update without a changelog as I
view those as a possible emergency update.

**Comment by daniel-araujo** [comment]
There be changelogs: https://github.com/daniel-araujo/click4ever/tree/v1.3.0#changelog

**Comment by kreezxil** [comment]
thank you. ;)
